# Generated by Django 2.2.12 on 2021-08-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('unit', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mileage', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
