# Generated by Django 2.2.12 on 2021-08-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.PositiveIntegerField(),
        ),
    ]
