# Generated by Django 2.2.12 on 2021-08-30 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_auto_20210829_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Mileage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('unit', models.ForeignKey(db_column='unit', on_delete=django.db.models.deletion.DO_NOTHING, to='api_basic.Vehicle')),
            ],
            options={
                'unique_together': {('unit', 'date')},
            },
        ),
    ]
